version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo
    
    steps:
      - checkout

      - run:
          name: Maven
          command: mvn package --show-version --batch-mode --errors

      - run:
          name: Archive
          command: |
            mkdir runestar-launcher
            cp README.md runestar-launcher
            cp LICENSE runestar-launcher
            cp client.prm runestar-launcher
            cp runestar-launcher.* runestar-launcher
            zip -r runestar-launcher.zip runestar-launcher
            tar -xzvf runestar-launcher.tar.gz runestar-launcher

      - run:
          name: GitHub Release
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" && -z "${CIRCLE_PULL_REQUEST}" ]]; then
              mvn github-release:release --settings .circleci/settings.xml
            fi